sequenceDiagram
    participant User
    participant MainWindow
    participant GroupManager
    participant Group

    activate User
    User->>MainWindow: start program
    deactivate User

    activate MainWindow
    MainWindow ->> GroupManager: Initialize groups
    deactivate MainWindow

    activate GroupManager

    alt if file doesn't exists
        GroupManager ->> MainWindow: "Couldn't load groups, because file '{TextManager.GroupsFileName}' not found!"
    else
        GroupManager->>GroupManager: Read groups
        activate GroupManager

        alt if can't deserialize json file
            GroupManager ->> MainWindow: "There was a problem reading {TextManager.GroupsFileName}"
        else
            loop
                alt if group name is null
                    GroupManager ->> MainWindow: "Can't add group, because the name is null!"
                else if group name is empty
                    GroupManager ->> MainWindow: "Can't add group, because the name is empty!"
                else if group driverless is null
                    GroupManager ->> MainWindow: "Can't add group, because driverless is null!"
                else if group customizable is null
                    GroupManager ->> MainWindow: "Can't add group, because customizable is null!"
                else if group attributes are null
                    GroupManager ->> MainWindow: "Can't add group, because attributes are null!"
                else
                    GroupManager ->> Group: Create new
                    activate Group
                    Group -->> GroupManager: Return new
                    deactivate Group

                    loop
                        alt if attribute name is null
                            GroupManager ->> MainWindow: "Can't add attribute, because name is null!"
                        else if attribute color is null
                            GroupManager ->> MainWindow: "Can't add attribute, because color is null!"
                        else if attribute name and color are not empty
                            GroupManager ->> Group: Add attribute
                            activate Group
                            deactivate Group
                        end
                    end
                    
                    activate GroupManager
                    GroupManager ->> GroupManager: Add group
                    deactivate GroupManager
                end
            end
        end

        deactivate GroupManager
    end
    
    deactivate GroupManager
