sequenceDiagram
  participant User
  participant InputFileSettings
  participant InputFileManager
  participant DataReader
  participant BackgroundWorker
  participant Channel
  participant GroupManager
  participant DriverlessInputFile
  participant SettingsMenu
  participant MenuManager
  participant TextManager
  participant InputFileChannelSettingsItem
  participant ImportantChannels
  participant InputFile

  %% InputFileSettings - row 204
  User ->> InputFileSettings: Click read file button
  activate User
  deactivate User

    activate InputFileSettings
    %% InputFileSettings - row 214
    opt if open file dialog returns true
      %% InputFileSettings - row 218
      InputFileSettings ->> InputFileManager: Get input file
        activate InputFileManager
          %% InputFileManager - row 28
          InputFileManager -->> InputFileSettings: Return input file
        deactivate InputFileManager

      %% InputFileSettings - row 218
      opt if file is new
        %% InputFileSettings - row 221
        InputFileSettings ->> DataReader: Create new
        activate DataReader
        DataReader -->> InputFileSettings: Return new
        deactivate DataReader

        activate DataReader
          %% InputFileSettings - row 221
          InputFileSettings ->> DataReader: Setup reader

          activate DataReader
            %% InputFileSettings - row 225
            InputFileSettings ->> DataReader: Read file

            %% DataReader - row 57
            alt if file doesn't exists
              DataReader ->> User: "{fileName} not found!"
              activate User
              deactivate User
            else
              %% DataReader - row 64
              DataReader ->> DataReader: Start worker
              activate DataReader
                %% DataReader - row 144
                DataReader ->> BackgroundWorker: Create new
                activate BackgroundWorker
                BackgroundWorker -->> DataReader: Return new
                deactivate BackgroundWorker

                %% DataReader - row 148
                par worker do work
                  activate BackgroundWorker
                    %% DataReader - row 156
                    DataReader -> BackgroundWorker: Worker do work
                      %% DataReader - row 67
                      DataReader ->> DataReader: Process file
                      activate DataReader
                        %% DataReader - row 69
                        alt if file length is 0
                          DataReader ->> User: "{fileName} is empty"
                          activate User
                          deactivate User
                        else
                          %% DataReader - row 83
                          loop in first row of the file
                            %% DataReader - row 85
                            alt if channel name is empty
                              DataReader ->> User: "Channels name is empty in {fileName}"
                              activate User
                              deactivate User
                            else
                              %% DataReader - row 90
                              DataReader ->> Channel: Create new
                              activate Channel
                                Channel -->> DataReader: Return new
                              deactivate Channel

                              %% DataReader - row 92
                              DataReader ->> GroupManager: Get groups
                              activate GroupManager
                                GroupManager -->> DataReader: Return groups
                              deactivate GroupManager

                              %% DataReader - row 92
                              loop in groups
                                %% DataReader - row 94
                                loop in group attributes
                                  %% DataReader - row 96
                                  opt attribute name is equals to channels name
                                    DataReader ->> Channel: set color to attribute color
                                    activate Channel
                                    deactivate Channel
                                  end
                                end
                              end
                            end
                          end

                          %% DataReader - row 108
                          loop while not end of stream
                            %% DataReader - row 111
                            loop in channels
                              %% DataReader - row 113
                              alt if row[i] is not empty
                                %% DataReader - row 119
                                alt if can't parse row[i] to number
                                  DataReader ->> User: "Can't convert {row[i]} into number in {fileName}"
                                  activate User
                                  deactivate User
                                end
                              end
                            end

                            %% DataReader - row 130
                            DataReader ->> DataReader: Report progress to worker
                            activate DataReader
                              %% DataReader - row 134
                              DataReader ->> BackgroundWorker: Report progress
                              activate BackgroundWorker
                              deactivate BackgroundWorker
                            deactivate DataReader
                          end

                        end
                      deactivate DataReader
                  deactivate BackgroundWorker
                and progress changed
                  Note over DataReader: Updates progress bar value
                and worker completed
                  %% DataReader - row 185
                  DataReader ->> InputFileManager: Add input file
                  activate InputFileManager
                  deactivate InputFileManager

                  %% DataReader - row 186
                  DataReader ->> InputFileManager: Set active input file to this
                  activate InputFileManager
                  deactivate InputFileManager

                  %% DataReader - row 187
                  DataReader ->> MenuManager: Get settings menu tab
                  activate MenuManager
                    MenuManager ->> TextManager: Get settings menu name
                    activate TextManager
                      TextManager -->> MenuManager: Return settings menu name
                    deactivate TextManager

                    MenuManager ->> SettingsMenu: Get files settings tab
                    activate SettingsMenu
                      SettingsMenu ->> TextManager: Get file settings tab name
                      activate TextManager
                        TextManager -->> SettingsMenu: Return file settings tab name
                      deactivate TextManager

                      SettingsMenu ->> InputFilesSettings: Add input file settings item
                      activate InputFilesSettings
                        %% InputFilesSettings - row 50
                        InputFilesSettings ->> InputFilesSettings: Initialize active channel
                        activate InputFilesSettings
                          %% InputFilesSettings - row 158
                          InputFilesSettings ->> InputFileManager: Get active input file
                          activate InputFileManager
                            InputFileManager -->> InputFilesSettings: Return active input file
                          deactivate InputFileManager

                          %% InputFilesSettings - row 159
                          opt if active input file is not null
                            %% InputFilesSettings - row 161
                            opt if activate input files channels length is greater than 0
                              Note over InputFilesSettings: Set active channel to activate input file first channel.
                            end
                          end
                        deactivate InputFilesSettings

                        %% InputFilesSettings - row 55
                        InputFilesSettings ->> InputFilesSettings: Initialize channel items
                        activate InputFilesSettings
                          %% InputFilesSettings - row 176
                          InputFilesSettings ->> InputFileManager: Get active input file
                          activate InputFileManager
                            InputFileManager -->> InputFilesSettings: Return active input file
                          deactivate InputFileManager

                          %% InputFilesSettings - row 177
                          opt if activate input file is not null
                            loop in activate input file channels
                              %% InputFilesSettings - row 192
                              InputFilesSettings ->> InputFilesSettings: Add input file channel settings item
                              activate InputFilesSettings
                                %% InputFilesSettings - row 194
                                InputFilesSettings ->> InputFileChannelSettingsItem: Create new
                                activate InputFileChannelSettingsItem
                                  InputFileChannelSettingsItem -->> InputFilesSettings: Return new
                                deactivate InputFileChannelSettingsItem
                              deactivate InputFilesSettings
                            end
                          end

                          %% InputFilesSettings - row 185
                          InputFilesSettings ->> InputFilesSettings: Update required channels
                          activate InputFilesSettings
                            %% InputFilesSettings - row 241
                            InputFilesSettings ->> InputFileManager: Get active input file
                            activate InputFileManager
                              InputFileManager -->> InputFilesSettings: Return active input file
                            deactivate InputFileManager

                            %% InputFilesSettings - row 243
                            opt if active input file is not null
                              alt if active input file is driverless
                                %% InputFilesSettings - row 247
                                InputFilesSettings ->> ImportantChannels: Get driverless important channels
                                activate ImportantChannels
                                  ImportantChannels -->> InputFilesSettings: Return driverless important channels
                                deactivate ImportantChannels

                                %% InputFilesSettings - row 247
                                loop in important driverless channels
                                  InputFilesSettings ->> InputFilesSettings: Add important channel name check box
                                  activate InputFilesSettings
                                  deactivate InputFilesSettings
                                end
                              else
                                Note over InputFilesSettings: TODO standarddal is
                              end
                            end
                          deactivate InputFilesSettings
                        deactivate InputFilesSettings

                        %% InputFilesSettings - row 56
                        InputFilesSettings ->> InputFilesSettings: Change all input file settings item color mode
                        activate InputFilesSettings
                        deactivate InputFilesSettings

                        %% InputFilesSettings - row 57
                        InputFilesSettings ->> InputFilesSettings: Add single input file settings item
                        activate InputFilesSettings
                          %% InputFilesSettings - row 147
                          InputFilesSettings ->> InputFileSettingsItem: Create new
                          activate InputFileSettingsItem
                            InputFileSettingsItem -->> InputFileSettings: Return new
                            %% InputFileSettingsItem - row 35
                            InputFileSettingsItem ->> InputFileSettingsItem: Change type image
                            activate InputFileSettingsItem
                            deactivate InputFileSettingsItem
                          deactivate InputFileSettingsItem

                          InputFileSettings ->> InputFileSettingsItem: Change color mode
                          activate InputFileSettingsItem
                          deactivate InputFileSettingsItem
                        deactivate InputFilesSettings
                      deactivate InputFilesSettings
                    deactivate SettingsMenu
                  deactivate MenuManager
                end

              deactivate DataReader
            end

          deactivate DataReader

        deactivate DataReader
      end
    end
    deactivate InputFileSettings