sequenceDiagram
    participant User
    participant MainWindow
    participant GroupManager
    participant Group
    participant MenuManager
    participant DriverlessMenu
    participant SettingsMenu
    participant InputFilesSettings
    participant GroupSettings
    participant InputFileManager
    participant GroupSettingsItem
    participant GroupSettingsAttribute

    activate User
    User->>MainWindow: start program
    deactivate User

    activate MainWindow
    MainWindow ->> GroupManager: Initialize groups
    deactivate MainWindow

    activate GroupManager

    alt if file doesn't exists
        GroupManager ->> MainWindow: "Couldn't load groups, because file '{TextManager.GroupsFileName}' not found!"
    else
        GroupManager->>GroupManager: Read groups
        activate GroupManager

        alt if can't deseralize json file
            GroupManager ->> MainWindow: "There was a problem reading {TextManager.GroupsFileName}"
        else
            loop
                alt if group name is null
                    GroupManager ->> MainWindow: "Can't add group, because the name is null!"
                else if group name is empty
                    GroupManager ->> MainWindow: "Can't add group, because the name is empty!"
                else if group driverless is null
                    GroupManager ->> MainWindow: "Can't add group, because driverless is null!"
                else if group customizable is null
                    GroupManager ->> MainWindow: "Can't add group, because customizable is null!"
                else if group attributes are null
                    GroupManager ->> MainWindow: "Can't add group, because attributes are null!"
                else
                    loop
                        alt if attribute name is null
                            GroupManager ->> MainWindow: "Can't add attribute, because name is null!"
                        else if aatribute color is null
                            GroupManager ->> MainWindow: "Can't add attribute, because color is null!"
                        else if attribute name and color are not empty
                            activate Group
                            GroupManager ->> Group: Add attribute
                            deactivate Group
                        end
                    end
                    
                    activate GroupManager
                    GroupManager ->> GroupManager: Add group
                    deactivate GroupManager
                end
            end
        end

        deactivate GroupManager
    end

    activate MainWindow
    MainWindow ->> MenuManager: Initialize menu tabs
    deactivate MainWindow

    activate MenuManager

    MenuManager ->> MenuManager: Add driverless menu tab
    activate MenuManager
    deactivate MenuManager

    MenuManager ->> MenuManager: Add settings menu tab
    activate MenuManager
    deactivate MenuManager
    
    activate SettingsMenu

    MenuManager ->> SettingsMenu: Create new
    activate SettingsMenu
    SettingsMenu -->> MenuManager: Return new
    deactivate SettingsMenu

    activate SettingsMenu
    SettingsMenu ->> SettingsMenu: Initialize settings tabs

    activate SettingsMenu
    SettingsMenu ->> SettingsMenu: Add input file settings tab
    SettingsMenu ->> InputFilesSettings: Create new
    activate InputFilesSettings
    InputFilesSettings -->> SettingsMenu: Return new
    deactivate InputFilesSettings
    deactivate SettingsMenu

    activate SettingsMenu
    SettingsMenu ->> SettingsMenu: Add group settings tab
    SettingsMenu ->> GroupSettings: Create new
    activate GroupSettings
    GroupSettings -->> SettingsMenu: Return new
    deactivate GroupSettings

    activate GroupSettings
    GroupSettings ->> GroupManager: Get groups length
    activate GroupManager
    GroupManager -->> GroupSettings: Return groups length
    deactivate GroupManager
    alt if groups has items
        GroupSettings ->> GroupManager: Get active group
        activate GroupManager
        GroupManager -->> GroupSettings: Return active group
        deactivate GroupManager

        alt if active group is driverless
            activate GroupSettings
            GroupSettings ->> GroupSettings: Destroy all active channel selectable attributes
            deactivate GroupSettings
        end

        activate GroupSettings
        GroupSettings ->> GroupSettings: Initialize active channel selectable attributes
        GroupSettings ->> GroupManager: Get active group
        activate GroupManager
        GroupManager -->> GroupSettings: Return active group
        deactivate GroupManager

        alt if active group is driverless
            GroupSettings ->> InputFileManager: Get selected driverless input file
            activate InputFileManager
            InputFileManager -->> GroupSettings: Return selected driverless input file
            deactivate InputFileManager
        end

        deactivate GroupSettings

        activate GroupSettings
        GroupSettings ->> GroupSettings: Initialize groups

        loop
            GroupSettings ->> GroupSettingsItem: Create new
            activate GroupSettingsItem
            GroupSettingsItem -->> GroupSettings: Return new
            deactivate GroupSettingsItem
            GroupSettings ->> GroupSettingsItem: Change color mode
            activate GroupSettingsItem
            deactivate GroupSettingsItem
        end

        GroupSettings ->> GroupManager: Get active group
        activate GroupManager
        GroupManager -->> GroupSettings: Return active group
        deactivate GroupManager

        SettingsMenu ->> SettingsMenu: Initialize attributes
        activate SettingsMenu

        GroupSettings ->> GroupManager: Get active group
        activate GroupManager
        GroupManager -->> GroupSettings: Return active group
        deactivate GroupManager

        loop in active group attributes
            GroupSettings ->> GroupSettingsAttribute: Create new
            activate GroupSettingsAttribute
            GroupSettingsAttribute -->> GroupSettings: Return new
            deactivate GroupSettingsAttribute
        end

        deactivate SettingsMenu
        deactivate GroupSettings

    end

    activate GroupSettings
    GroupSettings ->> GroupSettings: Initialize input files combo box

    GroupSettings ->> InputFileManager: Get input files
    activate InputFileManager
    InputFileManager -->> GroupSettings: Return input files
    deactivate InputFileManager

    loop in input files
        activate GroupSettings
        GroupSettings ->> GroupSettings: Add input file combo box item
        deactivate GroupSettings
    end

    deactivate GroupSettings

    deactivate GroupSettings

    deactivate SettingsMenu

    deactivate SettingsMenu

    deactivate SettingsMenu



    deactivate MenuManager
